"""initial schema

Revision ID: 8927b31b8c39
Revises: 
Create Date: 2026-01-16 10:10:30.862062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
# from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = '8927b31b8c39'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    print("Upgrade function called")
    print("postgresql:", postgresql)
    print("Creating users table")
    print("Executing select")
    op.execute("SELECT 1")
    print("Executed")
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # op.create_table('conversation_logs',
    # sa.Column('id', postgresql.UUID(), nullable=False),
    # sa.Column('user_id', postgresql.UUID(), nullable=False),
    # sa.Column('text_query', sa.Text(), nullable=True),
    # sa.Column('image_urls', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    # sa.Column('vlm_output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    # sa.Column('response_text', sa.Text(), nullable=False),
    # sa.Column('llm_model_name', sa.Text(), nullable=True),
    # sa.Column('vlm_model_name', sa.Text(), nullable=True),
    # sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    # sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.create_index('ix_conversation_user_id', 'conversation_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_conversation_user_id', table_name='conversation_logs')
    op.drop_table('conversation_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
