"""add conversation logs

Revision ID: bffc0ef01d48
Revises: ea97882a9369
Create Date: 2025-12-23 00:26:47.005532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bffc0ef01d48'
down_revision: Union[str, Sequence[str], None] = 'ea97882a9369'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('conversation_logs', 'llm_model_name',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('conversation_logs', 'vlm_model_name',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('conversation_logs', 'vlm_model_name',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('conversation_logs', 'llm_model_name',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
